Repository D4A-2019/Material, pull requests merged in 2020-07, with the labels that each got.

#8 Dalil component fix
  src/contents/chapter1.js
  src/dalil/README.md
  src/dalil/dalil.js
Labels: bug

#3 Add Drawer Navigation to Project
  package-lock.json
  package.json
  src/contents/chapter1.js
  src/contents/chapter10.js
  src/contents/chapter11.js
  src/contents/chapter12.js
  src/contents/chapter13.js
  src/contents/chapter14.js
  src/contents/chapter15.js
  src/contents/chapter2 copy.js
  src/contents/chapter3.js
  src/contents/chapter4.js
  src/contents/chapter5.js
  src/contents/chapter6.js
  src/contents/chapter7.js
  src/contents/chapter9.js
  src/contents/drawer_navigation/chapterNavigation.js
  src/contents/drawer_navigation/drawerBundle.js
  src/contents/drawer_navigation/drawerChapter10.js
  src/contents/drawer_navigation/drawerChapter11.js
  src/contents/drawer_navigation/drawerChapter12.js
  src/contents/drawer_navigation/drawerChapter13.js
  src/contents/drawer_navigation/drawerChapter14.js
  src/contents/drawer_navigation/drawerChapter15.js
  src/contents/drawer_navigation/drawerChapter2.js
  src/contents/drawer_navigation/drawerChapter3.js
  src/contents/drawer_navigation/drawerChapter4.js
  src/contents/drawer_navigation/drawerChapter5.js
  src/contents/drawer_navigation/drawerChapter6.js
  src/contents/drawer_navigation/drawerChapter7.js
  src/contents/drawer_navigation/drawerChapter8.js
  src/contents/drawer_navigation/drawerChapter9.js
  src/dalil/dalil.js
  src/index.js
  src/materialsScreen.js
Labels: enhancement

#34 About
  assets/images/instagramLogo.png
  package-lock.json
  package.json
  src/aboutScreen.js
Labels: enhancement

#33 Chapter1 2 3
  assets/audios/AlAraf-172.mp3
  assets/audios/AlBaqarah-147.mp3
  assets/audios/AlBaqarah-208.mp3
  assets/audios/AlBaqarah-256.mp3
  assets/audios/AlBaqarah-8.mp3
  assets/audios/AlFajr-(27-30).mp3
  assets/audios/AlHajj-54.mp3
  assets/audios/AlIsra-(23-24).mp3
  assets/audios/AlIsra-81.mp3
  assets/audios/AlJinn-14.mp3
  assets/audios/AlKafirun-(1-6).mp3
  assets/audios/AlMulk-2.mp3
  assets/audios/AlQasas-88.mp3
  assets/audios/AliImran-14.mp3
  assets/audios/AliImran-159.mp3
  assets/audios/AliImran-31.mp3
  assets/audios/AnNahl-97.mp3
  assets/audios/AnNisa-36.mp3
  assets/audios/ArRum-21.mp3
  assets/audios/ArRum-30.mp3
  assets/audios/AshSyams-(7-11).mp3
  assets/audios/AtTaubah-105.mp3
  assets/audios/AtTin-(4-5).mp3
  assets/audios/Luqman-(12-15).mp3
  assets/audios/Yunus-25.mp3
  package-lock.json
  package.json
  src/contents/chapter1.js
  src/contents/chapter2.js
  src/contents/chapter3.js
Labels: enhancement

#35 Basic front end
  app.json
  src/index.js
Labels: enhancement

#36 Chapter7 until chapter15
  assets/audios/Al-Anbiya-107.mp3
  src/contents/chapter10.js
  src/contents/chapter11.js
  src/contents/chapter12.js
  src/contents/chapter13.js
  src/contents/chapter14.js
  src/contents/chapter15.js
  src/contents/chapter2.js
  src/contents/chapter7.js
  src/contents/chapter8.js
  src/contents/chapter9.js
Labels: Content, enhancement

#37 Content bab4 bab5 bab6
  src/contents/chapter4.js
  src/contents/chapter5.js
  src/contents/chapter6.js
Labels: Content, enhancement

#38 Front end
  assets/images/icons/Icon-256px.png
  package.json
  src/aboutScreen.js
  src/contents/chapter1.js
  src/contents/chapter10.js
  src/contents/chapter11.js
  src/contents/chapter12.js
  src/contents/chapter13.js
  src/contents/chapter14.js
  src/contents/chapter15.js
  src/contents/chapter2.js
  src/contents/chapter3.js
  src/contents/chapter4.js
  src/contents/chapter5.js
  src/contents/chapter6.js
  src/contents/chapter7.js
  src/contents/chapter8.js
  src/contents/chapter9.js
  src/contents/drawer_navigation/chapterNavigation.js
  src/contents/drawer_navigation/drawerChapter4.js
  src/index.js
  src/materialsScreen.js
  yarn.lock
Labels: enhancement

#39 Deployment preparation
  app.json
  src/index.js
Labels: enhancement
